/**
 * An anonymised copy of one real account's survey rows, as they stood at
 * 2:43 pm ET on 24 September 2026 — the account the client-document redesign
 * was built against. Every number, date, stage, status and credit is exactly as
 * recorded; the account, survey titles, people and ids are replaced. Kept real
 * because the awkward cases are real: two delivered surveys never priced, one
 * priced survey with no dates at all, a count typed in mid-field, a survey
 * delivered at 9:53 pm ET, an empty duplicate contract.
 *
 * Generated once by a read-only script; do not hand-edit the numbers.
 */
import type { AccountProject } from '@/components/sales/AccountDetail'
import type { Term } from './credits'

export const FIXTURE_CLIENT = { id: 'cl-fixture', name: 'Fixture Capital', code: 'Cl00000' }

/** When the snapshot was taken: 2:43 pm ET on 24 September 2026. */
export const FIXTURE_NOW = new Date('2026-09-24T18:43:00Z')

export const FIXTURE_TERMS: Term[] = [
  {
    "id": "term-2026",
    "name": "2026 Contract",
    "credits_total": 375,
    "starts_on": "2026-03-30",
    "renews_on": "2027-03-29"
  },
  {
    "id": "term-dup",
    "name": "2026 - 2027 Contract",
    "credits_total": null,
    "starts_on": null,
    "renews_on": null
  }
]

export const FIXTURE_ROWS: AccountProject[] = [
  {
    "id": "p-00466",
    "project_code": "PR00466",
    "project_name": "Study Delta - Audience Delta",
    "board_column": "Fielding",
    "status": "Open",
    "phase": "Active",
    "scoping_stage": "Awaiting Approval",
    "n_target": 75,
    "n_target_max": null,
    "n_collected": 20,
    "n_actual": null,
    "credits": 66,
    "term_id": "term-2026",
    "submitted_date": "2026-09-21",
    "launch_date": "2026-09-22",
    "deliver_date": "2026-09-28",
    "delivered_at": null,
    "requested_by_name": "Requester One",
    "longitudinal": false,
    "rerun_number": 1
  },
  {
    "id": "p-00257",
    "project_code": "PR00257",
    "project_name": "Study Alpha",
    "board_column": "Fielding",
    "status": "Open",
    "phase": "Active",
    "scoping_stage": "Awaiting Approval",
    "n_target": 50,
    "n_target_max": 50,
    "n_collected": 22,
    "n_actual": 7,
    "credits": 13,
    "term_id": "term-2026",
    "submitted_date": "2026-07-24",
    "launch_date": "2026-07-24",
    "deliver_date": "2026-09-23",
    "delivered_at": null,
    "requested_by_name": "Requester Two",
    "longitudinal": false,
    "rerun_number": 1
  },
  {
    "id": "p-00433",
    "project_code": "PR00433",
    "project_name": "Study Echo - Audience Echo",
    "board_column": "Delivery",
    "status": "Closed",
    "phase": "Active",
    "scoping_stage": "New Inquiry",
    "n_target": 45,
    "n_target_max": 45,
    "n_collected": 56,
    "n_actual": 48,
    "credits": 36,
    "term_id": "term-2026",
    "submitted_date": "2026-09-14",
    "launch_date": "2026-09-14",
    "deliver_date": "2026-09-22",
    "delivered_at": "2026-09-18T17:49:22.149345+00:00",
    "requested_by_name": "Requester One",
    "longitudinal": false,
    "rerun_number": 1
  },
  {
    "id": "p-00390",
    "project_code": "PR00390",
    "project_name": "Study Foxtrot - Audience Foxtrot",
    "board_column": "Delivery",
    "status": "Closed",
    "phase": "Active",
    "scoping_stage": "New Inquiry",
    "n_target": 50,
    "n_target_max": 50,
    "n_collected": 60,
    "n_actual": 50,
    "credits": 44,
    "term_id": "term-2026",
    "submitted_date": "2026-08-31",
    "launch_date": "2026-08-31",
    "deliver_date": "2026-09-14",
    "delivered_at": "2026-09-14T20:39:07.238361+00:00",
    "requested_by_name": "Requester One",
    "longitudinal": false,
    "rerun_number": 1
  },
  {
    "id": "p-00382",
    "project_code": "PR00382",
    "project_name": "Study Golf - Audience Golf",
    "board_column": "Delivery",
    "status": "Closed",
    "phase": "Active",
    "scoping_stage": "Awaiting Approval",
    "n_target": 100,
    "n_target_max": 100,
    "n_collected": 144,
    "n_actual": 100,
    "credits": 58,
    "term_id": "term-2026",
    "submitted_date": "2026-08-27",
    "launch_date": "2026-08-28",
    "deliver_date": "2026-09-11",
    "delivered_at": "2026-09-14T13:17:35.274602+00:00",
    "requested_by_name": "Requester One",
    "longitudinal": false,
    "rerun_number": 1
  },
  {
    "id": "p-00396",
    "project_code": "PR00396",
    "project_name": "Study India - Audience India (Full Launch)",
    "board_column": "Delivery",
    "status": "Closed",
    "phase": "Active",
    "scoping_stage": null,
    "n_target": 200,
    "n_target_max": 200,
    "n_collected": 595,
    "n_actual": 220,
    "credits": 15,
    "term_id": "term-2026",
    "submitted_date": null,
    "launch_date": "2026-08-31",
    "deliver_date": "2026-09-02",
    "delivered_at": "2026-09-03T12:59:37.98268+00:00",
    "requested_by_name": "Requester One",
    "longitudinal": false,
    "rerun_number": 2
  },
  {
    "id": "p-00378",
    "project_code": "PR00378",
    "project_name": "Study Juliet - Audience Juliet",
    "board_column": "Delivery",
    "status": "Closed",
    "phase": "Active",
    "scoping_stage": "Awaiting Approval",
    "n_target": 50,
    "n_target_max": 50,
    "n_collected": 62,
    "n_actual": 52,
    "credits": 35,
    "term_id": "term-2026",
    "submitted_date": "2026-08-24",
    "launch_date": "2026-08-27",
    "deliver_date": "2026-08-31",
    "delivered_at": "2026-08-31T19:30:16.203483+00:00",
    "requested_by_name": "Requester One",
    "longitudinal": false,
    "rerun_number": 1
  },
  {
    "id": "p-00376",
    "project_code": "PR00376",
    "project_name": "Study India - Audience India (Soft Launch)",
    "board_column": "Delivery",
    "status": "Closed",
    "phase": "Active",
    "scoping_stage": "Pricing Discussion",
    "n_target": 20,
    "n_target_max": 20,
    "n_collected": 31,
    "n_actual": 25,
    "credits": 2,
    "term_id": "term-2026",
    "submitted_date": "2026-08-24",
    "launch_date": "2026-08-26",
    "deliver_date": "2026-08-28",
    "delivered_at": "2026-08-28T15:29:58.494569+00:00",
    "requested_by_name": "Requester One",
    "longitudinal": false,
    "rerun_number": 1
  },
  {
    "id": "p-00358",
    "project_code": "PR00358",
    "project_name": "Study Kilo - Audience Kilo",
    "board_column": "Delivery",
    "status": "Closed",
    "phase": "Active",
    "scoping_stage": "Awaiting Approval",
    "n_target": 100,
    "n_target_max": 100,
    "n_collected": 117,
    "n_actual": 97,
    "credits": 58,
    "term_id": "term-2026",
    "submitted_date": "2026-08-14",
    "launch_date": "2026-08-17",
    "deliver_date": "2026-08-24",
    "delivered_at": "2026-08-25T01:53:27.453012+00:00",
    "requested_by_name": "Requester One",
    "longitudinal": false,
    "rerun_number": 1
  },
  {
    "id": "p-00261",
    "project_code": "PR00261",
    "project_name": "Study Lima",
    "board_column": "Delivery",
    "status": "Closed",
    "phase": "Active",
    "scoping_stage": "Awaiting Approval",
    "n_target": 100,
    "n_target_max": 100,
    "n_collected": 171,
    "n_actual": 122,
    "credits": 68,
    "term_id": "term-2026",
    "submitted_date": "2026-07-28",
    "launch_date": "2026-07-29",
    "deliver_date": "2026-08-07",
    "delivered_at": "2026-08-07T16:10:08.557329+00:00",
    "requested_by_name": "Requester Four",
    "longitudinal": false,
    "rerun_number": 1
  },
  {
    "id": "p-00075",
    "project_code": "PR00075",
    "project_name": "Study Mike",
    "board_column": "Delivery",
    "status": "Closed",
    "phase": "Active",
    "scoping_stage": "New Inquiry",
    "n_target": 115,
    "n_target_max": 115,
    "n_collected": 120,
    "n_actual": 115,
    "credits": null,
    "term_id": "term-2026",
    "submitted_date": null,
    "launch_date": null,
    "deliver_date": "2026-03-27",
    "delivered_at": "2026-09-10T20:04:47.46853+00:00",
    "requested_by_name": null,
    "longitudinal": false,
    "rerun_number": 1
  },
  {
    "id": "p-00054",
    "project_code": "PR00054",
    "project_name": "Study November",
    "board_column": "Delivery",
    "status": "Closed",
    "phase": "Active",
    "scoping_stage": "New Inquiry",
    "n_target": 115,
    "n_target_max": 115,
    "n_collected": 99,
    "n_actual": 99,
    "credits": null,
    "term_id": "term-2026",
    "submitted_date": null,
    "launch_date": null,
    "deliver_date": "2026-03-27",
    "delivered_at": "2026-09-08T19:59:11.612125+00:00",
    "requested_by_name": null,
    "longitudinal": false,
    "rerun_number": 1
  },
  {
    "id": "p-00479",
    "project_code": "PR00479",
    "project_name": "Study Kappa (Part B) - Audience Kappa",
    "board_column": "Doc Programming",
    "status": "Open",
    "phase": "Active",
    "scoping_stage": "New Inquiry",
    "n_target": 100,
    "n_target_max": 100,
    "n_collected": 0,
    "n_actual": null,
    "credits": null,
    "term_id": null,
    "submitted_date": null,
    "launch_date": null,
    "deliver_date": null,
    "delivered_at": null,
    "requested_by_name": "Requester Three",
    "longitudinal": true,
    "rerun_number": 1
  },
  {
    "id": "p-00151",
    "project_code": "PR00151",
    "project_name": "Study Oscar",
    "board_column": "Delivery",
    "status": "Closed",
    "phase": "Active",
    "scoping_stage": "New Inquiry",
    "n_target": null,
    "n_target_max": null,
    "n_collected": 481,
    "n_actual": null,
    "credits": 15,
    "term_id": "term-2026",
    "submitted_date": null,
    "launch_date": null,
    "deliver_date": null,
    "delivered_at": null,
    "requested_by_name": null,
    "longitudinal": false,
    "rerun_number": 1
  },
  {
    "id": "p-00478",
    "project_code": "PR00478",
    "project_name": "Study Kappa (Part A) - Audience Kappa",
    "board_column": "Doc Programming",
    "status": "Open",
    "phase": "Active",
    "scoping_stage": "New Inquiry",
    "n_target": 100,
    "n_target_max": 100,
    "n_collected": 0,
    "n_actual": null,
    "credits": null,
    "term_id": null,
    "submitted_date": null,
    "launch_date": null,
    "deliver_date": null,
    "delivered_at": null,
    "requested_by_name": "Requester Three",
    "longitudinal": true,
    "rerun_number": 1
  }
]

/** Surveys whose n_collected was never recorded (no freshness row). */
export const FIXTURE_NEVER_RECORDED: string[] = ["p-00075","p-00054","p-00478","p-00479"]
